version: "3"

services:
  php:
    container_name: php
    build:
      context: ./php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - '../:/var/www/symfony/'
      - './php/php.ini:/usr/local/etc/php/conf.d/docker-php-config.ini'
    networks:
      - symfony
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - '../:/var/www/symfony/'
    ports:
      - 80:80
    networks:
      - symfony
    env_file:
      - .env.nginx
  db:
    container_name: db
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "git_webhook_handler_db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - symfony

volumes:
  git_webhook_handler_db:

networks:
  symfony: